- name: install PG HA
  hosts: postgres_nodes
  gather_facts: True
  any_errors_fatal: True
  vars:
    postgres_ha_cluster_master_host: "{{ hosts[0] }}"
    postgres_ha_cluster_vip: 192.168.0.
    postgres_ha_pg_repl_pass: MySuperSecretDBPass
    postgres_ha_cluster_ha_password: AnotherSuperSecretPass1234
    postgres_ha_cluster_ha_password_hash: '$6$mHeZ7/LD1y.........7VJYu.'
  pre_tasks:
    - name: disable firewall
      service: name=firewalld state=stopped enabled=no
  roles:
     - postgres-ha