---
- hosts: sparknodes
  vars:
   host_ip: '{{ ansible_default_ipv4["address"] }}'   
  tasks:   
   - name: Add hostname to /etc/hosts file
     become: true
     lineinfile:
      dest: /etc/hosts
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"      
     with_items:
      - { regexp: '^\s*127.0.0.1\s*localhost\s*$', line: '127.0.0.1 localhost localhost.localdomain {{ ansible_hostname }}' }